# US Population Data

Chanin Nantasenamat, Ph.D.

## Load data

In [1]:
import pandas as pd

df_overview = pd.read_csv('data/staff-info.csv')
df_overview

,Staff ID,Name,Gender,IAEA Profession,Nationality,iso_alpha,Academic,Pre-IAEA Work Experience,Generational
0,1001,John Smith,Male,Inspectors,United States,USA,Nuclear Engineer,Nuclear Energy,Generation X
1,1002,Alice Johnson,Female,Information Technology,Canada,CAN,Computer Science,Government,Millennials
2,1003,Mohammed Al-Farsi,Male,Laboratory Specialists,Saudi Arabia,SAU,Chemistry,Academia,Generation Z
3,1004,Anna Müller,Female,Information Analysts,Germany,DEU,Information Science,NGO,Baby Boomers
4,1005,Juan Perez,Male,Policy&Management Coordination,Spain,ESP,Int'l Relations,Health,Generation X
5,1006,Chen Wei,Male,Inspectors,China,CHN,Nuclear Physics,Nuclear Energy,Generation Z
6,1007,Emily Brown,Female,Information Technology,United Kingdom,GBR,Computer Engineering,Government,Millennials
7,1008,Ravi Patel,Male,Laboratory Specialists,India,IND,Chemical Engineering,Academia,Generation Y
8,1009,Maria Santos,Female,Information Analysts,Brazil,BRA,Library Science,NGO,Baby Boomers
9,1010,Mustafa Hassan,Male,Policy&Management Coordination,Egypt,EGY,Political Science,Government,Generation X
10,1011,Sophie Dupont,Female,Inspectors,France,FRA,Nuclear Engineering,Nuclear Energy,Millennials
11,1012,Kim Min-ji,Female,Information Technology,South Korea,KOR,Software Engineering,Health,Generation Z
12,1013,Alexander Ivanov,Male,Laboratory Specialists,Russia,RUS,Biochemistry,Academia,Generation X
13,1014,Li Wei,Female,Information Analysts,China,CHN,Data Science,NGO,Generation Y
14,1015,Lisa Müller,Female,Policy&Management Coordination,Germany,DEU,Public Policy,Government,Baby Boomers
15,1016,Antonio Lopez,Male,Inspectors,Spain,ESP,Physics,Nuclear Energy,Generation X
16,1017,Emily Johnson,Female,Information Technology,United States,USA,Computer Science,Health,Generation Z
17,1018,Rahul Singh,Male,Laboratory Specialists,India,IND,Biotechnology,Academia,Generation Y
18,1019,Ana Silva,Female,Information Analysts,Brazil,BRA,Information Systems,NGO,Generation X
19,1020,Ahmed Mahmoud,Male,Policy&Management Coordination,Egypt,EGY,Management,Government,Millennials
20,1021,Sarah Dubois,Female,Inspectors,France,FRA,Nuclear Physics,Nuclear Energy,Baby Boomers
21,1022,Park Joon-ho,Male,Information Technology,South Korea,KOR,Information Technology,NGO,Generation Z
22,1023,Ivan Petrov,Male,Laboratory Specialists,Russia,RUS,Chemistry,Academia,Generation Y
23,1024,Wang Lei,Male,Information Analysts,China,CHN,Computer Engineering,Health,Generation X
24,1025,Maria Garcia,Female,Policy&Management Coordination,Spain,ESP,Economics,Government,Generation Z
25,1026,David Miller,Male,Inspectors,United States,USA,Nuclear Engineering,Nuclear Energy,Generation Y
26,1027,Lucia Costa,Female,Information Technology,Portugal,PRT,Computer Science,NGO,Generation X
27,1028,Sandeep Kumar,Male,Laboratory Specialists,India,IND,Chemistry,Health,Millennials
28,1029,Carla Rodriguez,Female,Information Analysts,Brazil,BRA,Library Science,Academia,Generation Z
29,1030,Khalid Ibrahim,Male,Policy&Management Coordination,Egypt,EGY,Public Administration,Government,Generation Y
30,1031,Elena Dubrovna,Female,Inspectors,Russia,RUS,Nuclear Physics,Nuclear Energy,Generation X
31,1032,Liu Hui,Male,Information Technology,China,CHN,Software Engineering,NGO,Generation Z
32,1033,Emma Smith,Female,Laboratory Specialists,United Kingdom,GBR,Biology,Academia,Generation Y
33,1034,Ravi Patel,Male,Information Analysts,India,IND,Data Science,Health,Generation X
34,1035,Ana Santos,Female,Policy&Management Coordination,Brazil,BRA,Public Policy,Government,Generation Z
35,1036,Ahmed Hassan,Male,Inspectors,Egypt,EGY,Political Science,Nuclear Energy,Generation Y
36,1037,Sophie Leroux,Female,Information Technology,France,FRA,Computer Engineering,NGO,Generation X
37,1038,Chen Wei,Male,Laboratory Specialists,China,CHN,Chemical Engineering,Academia,Millennials
38,1039,Olga Ivanova,Female,Information Analysts,Russia,RUS,Information Systems,NGO,Generation Z
39,1040,Li Ming,Male,Policy&Management Coordination,China,CHN,Management,Government,Generation Y
40,1041,Lucas Silva,Male,Inspectors,Brazil,BRA,Nuclear Physics,Nuclear Energy,Generation X
41,1042,Jung Eun-ji,Female,Information Technology,South Korea,KOR,Information Technology,Health,Millennials
42,1043,Sergei Petrov,Male,Laboratory Specialists,Russia,RUS,Biochemistry,NGO,Generation Z
43,1044,Wang Fang,Male,Information Analysts,China,CHN,Computer Engineering,Academia,Generation Y
44,1045,Andrea Lopez,Female,Policy&Management Coordination,Spain,ESP,Economics,Government,Generation X
45,1046,Michael Brown,Male,Inspectors,United States,USA,Nuclear Engineering,Nuclear Energy,Millennials
46,1047,Marta Costa,Female,Information Technology,Portugal,PRT,Computer Science,Health,Generation Z
47,1048,Rajesh Kumar,Male,Laboratory Specialists,India,IND,Chemistry,Academia,Generation Y
48,1049,Juliana Rodriguez,Female,Information Analysts,Brazil,BRA,Library Science,NGO,Generation X
49,1050,Yousef Ahmed,Male,Policy&Management Coordination,Egypt,EGY,Public Administration,Government,Generation Z

In [2]:
filtered_data = df_overview[(df_overview['Nationality'] == "China")].reset_index(drop=True)

filtered_data

,Staff ID,Name,Gender,IAEA Profession,Nationality,iso_alpha,Academic,Pre-IAEA Work Experience,Generational
0,1006,Chen Wei,Male,Inspectors,China,CHN,Nuclear Physics,Nuclear Energy,Generation Z
1,1014,Li Wei,Female,Information Analysts,China,CHN,Data Science,NGO,Generation Y
2,1024,Wang Lei,Male,Information Analysts,China,CHN,Computer Engineering,Health,Generation X
3,1032,Liu Hui,Male,Information Technology,China,CHN,Software Engineering,NGO,Generation Z
4,1038,Chen Wei,Male,Laboratory Specialists,China,CHN,Chemical Engineering,Academia,Millennials
5,1040,Li Ming,Male,Policy&Management Coordination,China,CHN,Management,Government,Generation Y
6,1044,Wang Fang,Male,Information Analysts,China,CHN,Computer Engineering,Academia,Generation Y

In [9]:
for idx, name in enumerate(filtered_data["Name"]):
    print(idx)
    print(name)

0
Chen Wei
1
Li Wei
2
Wang Lei
3
Liu Hui
4
Chen Wei
5
Li Ming
6
Wang Fang

In [7]:
nationality_distribution.columns = ['iso_alpha', 'count']

In [8]:
nationality_distribution

         iso_alpha  count
0            China      7
1           Brazil      6
2            India      5
3            Egypt      5
4           Russia      5
5    United States      4
6            Spain      4
7           France      3
8      South Korea      3
9          Germany      2
10  United Kingdom      2
11        Portugal      2
12          Canada      1
13    Saudi Arabia      1

In [9]:
diversity_distribution = df_overview['Generational'].value_counts()

In [15]:
diversity_distribution

Generational
Generation X    14
Generation Z    13
Generation Y    11
Millennials      8
Baby Boomers     4
Name: count, dtype: int64

In [16]:
diversity_distribution

Generational
Generation X    14
Generation Z    13
Generation Y    11
Millennials      8
Baby Boomers     4
Name: count, dtype: int64

In [3]:
gender_distribution = df_overview['Gender'].value_counts()

In [5]:
gender_distribution.Male

28

In [3]:
import streamlit as st
colms = st.columns((1, 2, 2, 1, 1))
fields = ["№", 'email', 'uid', 'verified', "action"]
for col, field_name in zip(colms, fields):
    # header
    col.write(field_name)

2024-03-14 09:02:54.920
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /home/vscode/.local/lib/python3.11/site-packages/ipykernel_launcher.py [ARGUMENTS]

## Data pre-processing

In [6]:
# Reshape the DataFrame
df_reshaped = pd.melt(df, id_vars=['states', 'states_code', 'id'], var_name='year', value_name='population')

# Convert 'year' column values to integers
df_reshaped['states'] = df_reshaped['states'].astype(str)
df_reshaped['year'] = df_reshaped['year'].astype(int)
df_reshaped['population'] = df_reshaped['population'].str.replace(',', '').astype(int)

df_reshaped

            states states_code  id  year  population
0          Alabama          AL   1  2010     4785437
1           Alaska          AK   2  2010      713910
2          Arizona          AZ   4  2010     6407172
3         Arkansas          AR   5  2010     2921964
4       California          CA   6  2010    37319502
..             ...         ...  ..   ...         ...
515     Washington          WA  53  2019     7614893
516  West Virginia          WV  54  2019     1792147
517      Wisconsin          WI  55  2019     5822434
518        Wyoming          WY  56  2019      578759
519    Puerto Rico          PR  72  2019     3193694

[520 rows x 5 columns]

In [7]:
# Save reshaped data to CSV
df_reshaped.to_csv('us-population-2010-2019-reshaped.csv')

In [8]:
# Subset dataframe by year
selected_year = 2019
df_selected_year = df_reshaped[df_reshaped.year == selected_year]
df_selected_year

                   states states_code  id  year  population
468               Alabama          AL   1  2019     4903185
469                Alaska          AK   2  2019      731545
470               Arizona          AZ   4  2019     7278717
471              Arkansas          AR   5  2019     3017804
472            California          CA   6  2019    39512223
473              Colorado          CO   8  2019     5758736
474           Connecticut          CT   9  2019     3565287
475              Delaware          DE  10  2019      973764
476  District of Columbia          DC  11  2019      705749
477               Florida          FL  12  2019    21477737
478               Georgia          GA  13  2019    10617423
479                Hawaii          HI  15  2019     1415872
480                 Idaho          ID  16  2019     1787065
481              Illinois          IL  17  2019    12671821
482               Indiana          IN  18  2019     6732219
483                  Iowa          IA  19  2019     3155070
484                Kansas          KS  20  2019     2913314
485              Kentucky          KY  21  2019     4467673
486             Louisiana          LA  22  2019     4648794
487                 Maine          ME  23  2019     1344212
488              Maryland          MD  24  2019     6045680
489         Massachusetts          MA  25  2019     6892503
490              Michigan          MI  26  2019     9986857
491             Minnesota          MN  27  2019     5639632
492           Mississippi          MS  28  2019     2976149
493              Missouri          MO  29  2019     6137428
494               Montana          MT  30  2019     1068778
495              Nebraska          NE  31  2019     1934408
496                Nevada          NV  32  2019     3080156
497         New Hampshire          NH  33  2019     1359711
498            New Jersey          NJ  34  2019     8882190
499            New Mexico          NM  35  2019     2096829
500              New York          NY  36  2019    19453561
501        North Carolina          NC  37  2019    10488084
502          North Dakota          ND  38  2019      762062
503                  Ohio          OH  39  2019    11689100
504              Oklahoma          OK  40  2019     3956971
505                Oregon          OR  41  2019     4217737
506          Pennsylvania          PA  42  2019    12801989
507          Rhode Island          RI  44  2019     1059361
508        South Carolina          SC  45  2019     5148714
509          South Dakota          SD  46  2019      884659
510             Tennessee          TN  47  2019     6829174
511                 Texas          TX  48  2019    28995881
512                  Utah          UT  49  2019     3205958
513               Vermont          VT  50  2019      623989
514              Virginia          VA  51  2019     8535519
515            Washington          WA  53  2019     7614893
516         West Virginia          WV  54  2019     1792147
517             Wisconsin          WI  55  2019     5822434
518               Wyoming          WY  56  2019      578759
519           Puerto Rico          PR  72  2019     3193694

In [9]:
# Sort by year
df_selected_year_sorted = df_selected_year.sort_values(by="population", ascending=False)
df_selected_year_sorted

                   states states_code  id  year  population
472            California          CA   6  2019    39512223
511                 Texas          TX  48  2019    28995881
477               Florida          FL  12  2019    21477737
500              New York          NY  36  2019    19453561
506          Pennsylvania          PA  42  2019    12801989
481              Illinois          IL  17  2019    12671821
503                  Ohio          OH  39  2019    11689100
478               Georgia          GA  13  2019    10617423
501        North Carolina          NC  37  2019    10488084
490              Michigan          MI  26  2019     9986857
498            New Jersey          NJ  34  2019     8882190
514              Virginia          VA  51  2019     8535519
515            Washington          WA  53  2019     7614893
470               Arizona          AZ   4  2019     7278717
489         Massachusetts          MA  25  2019     6892503
510             Tennessee          TN  47  2019     6829174
482               Indiana          IN  18  2019     6732219
493              Missouri          MO  29  2019     6137428
488              Maryland          MD  24  2019     6045680
517             Wisconsin          WI  55  2019     5822434
473              Colorado          CO   8  2019     5758736
491             Minnesota          MN  27  2019     5639632
508        South Carolina          SC  45  2019     5148714
468               Alabama          AL   1  2019     4903185
486             Louisiana          LA  22  2019     4648794
485              Kentucky          KY  21  2019     4467673
505                Oregon          OR  41  2019     4217737
504              Oklahoma          OK  40  2019     3956971
474           Connecticut          CT   9  2019     3565287
512                  Utah          UT  49  2019     3205958
519           Puerto Rico          PR  72  2019     3193694
483                  Iowa          IA  19  2019     3155070
496                Nevada          NV  32  2019     3080156
471              Arkansas          AR   5  2019     3017804
492           Mississippi          MS  28  2019     2976149
484                Kansas          KS  20  2019     2913314
499            New Mexico          NM  35  2019     2096829
495              Nebraska          NE  31  2019     1934408
516         West Virginia          WV  54  2019     1792147
480                 Idaho          ID  16  2019     1787065
479                Hawaii          HI  15  2019     1415872
497         New Hampshire          NH  33  2019     1359711
487                 Maine          ME  23  2019     1344212
494               Montana          MT  30  2019     1068778
507          Rhode Island          RI  44  2019     1059361
475              Delaware          DE  10  2019      973764
509          South Dakota          SD  46  2019      884659
502          North Dakota          ND  38  2019      762062
469                Alaska          AK   2  2019      731545
476  District of Columbia          DC  11  2019      705749
513               Vermont          VT  50  2019      623989
518               Wyoming          WY  56  2019      578759

In [10]:
# Calculate population difference between selected and previous year
def calculate_population_difference(input_df, input_year):
  selected_year_data = input_df[input_df['year'] == input_year].reset_index()
  previous_year_data = input_df[input_df['year'] == input_year - 1].reset_index()
  selected_year_data['population_difference'] = selected_year_data.population.sub(previous_year_data.population, fill_value=0)
  selected_year_data['population_difference_absolute'] = abs(selected_year_data['population_difference'])
  return pd.concat([selected_year_data.states, selected_year_data.id, selected_year_data.population, selected_year_data.population_difference, selected_year_data.population_difference_absolute], axis=1).sort_values(by="population_difference", ascending=False)

df_population_difference_sorted = calculate_population_difference(df_reshaped, selected_year)
df_population_difference_sorted

,states,id,population,population_difference,population_difference_absolute
43,Texas,48,28995881,367215,367215
9,Florida,12,21477737,233420,233420
2,Arizona,4,7278717,120693,120693
33,North Carolina,37,10488084,106469,106469
10,Georgia,13,10617423,106292,106292
47,Washington,53,7614893,91024,91024
5,Colorado,8,5758736,67449,67449
40,South Carolina,45,5148714,64558,64558
42,Tennessee,47,6829174,57543,57543
28,Nevada,32,3080156,52815,52815
44,Utah,49,3205958,52408,52408
4,California,6,39512223,50635,50635
14,Indiana,18,6732219,36722,36722
12,Idaho,16,1787065,36529,36529
37,Oregon,41,4217737,35851,35851
46,Virginia,51,8535519,34233,34233
23,Minnesota,27,5639632,33383,33383
36,Oklahoma,40,3956971,16736,16736
25,Missouri,29,6137428,15805,15805
0,Alabama,1,4903185,15504,15504
49,Wisconsin,55,5822434,15028,15028
35,Ohio,39,11689100,12759,12759
20,Maryland,24,6045680,9878,9878
21,Massachusetts,25,6892503,9868,9868
27,Nebraska,31,1934408,8794,8794
7,Delaware,10,973764,8285,8285
26,Montana,30,1068778,8113,8113
3,Arkansas,5,3017804,8071,8071
17,Kentucky,21,4467673,6520,6520
15,Iowa,19,3155070,6452,6452
29,New Hampshire,33,1359711,6246,6246
41,South Dakota,46,884659,5961,5961
19,Maine,23,1344212,5155,5155
8,District of Columbia,11,705749,4202,4202
31,New Mexico,35,2096829,4088,4088
34,North Dakota,38,762062,3982,3982
22,Michigan,26,9986857,2785,2785
16,Kansas,20,2913314,1955,1955
50,Wyoming,56,578759,1158,1158
39,Rhode Island,44,1059361,1074,1074
38,Pennsylvania,42,12801989,1067,1067
51,Puerto Rico,72,3193694,340,340
45,Vermont,50,623989,-369,369
1,Alaska,2,731545,-3594,3594
30,New Jersey,34,8882190,-3835,3835
11,Hawaii,15,1415872,-4721,4721
24,Mississippi,28,2976149,-4871,4871
6,Connecticut,9,3565287,-6233,6233
18,Louisiana,22,4648794,-10896,10896
48,West Virginia,54,1792147,-12144,12144
13,Illinois,17,12671821,-51250,51250
32,New York,36,19453561,-76790,76790

In [11]:
# Filter states with population difference > 50000
df_greater_50000 = df_population_difference_sorted[df_population_difference_sorted.population_difference_absolute > 50000]
df_greater_50000

,states,id,population,population_difference,population_difference_absolute
43,Texas,48,28995881,367215,367215
9,Florida,12,21477737,233420,233420
2,Arizona,4,7278717,120693,120693
33,North Carolina,37,10488084,106469,106469
10,Georgia,13,10617423,106292,106292
47,Washington,53,7614893,91024,91024
5,Colorado,8,5758736,67449,67449
40,South Carolina,45,5148714,64558,64558
42,Tennessee,47,6829174,57543,57543
28,Nevada,32,3080156,52815,52815
44,Utah,49,3205958,52408,52408
4,California,6,39512223,50635,50635
13,Illinois,17,12671821,-51250,51250
32,New York,36,19453561,-76790,76790

In [12]:
# % of States with population difference > 50000
int((len(df_greater_50000)/df_population_difference_sorted.states.nunique())*100)

26

## Plots

### Heatmap

In [13]:
import altair as alt

alt.themes.enable("dark")

heatmap = alt.Chart(df_reshaped).mark_rect().encode(
        y=alt.Y('year:O', axis=alt.Axis(title="Year", titleFontSize=16, titlePadding=15, titleFontWeight=900, labelAngle=0)),
        x=alt.X('states:O', axis=alt.Axis(title="States", titleFontSize=16, titlePadding=15, titleFontWeight=900)),
        color=alt.Color('max(population):Q',
                         legend=alt.Legend(title=" "),
                         scale=alt.Scale(scheme="blueorange")),
        stroke=alt.value('black'),
        strokeWidth=alt.value(0.25),
        #tooltip=[
        #    alt.Tooltip('year:O', title='Year'),
        #    alt.Tooltip('population:Q', title='Population')
        #]
    ).properties(width=900
    #).configure_legend(orient='bottom', titleFontSize=16, labelFontSize=14, titlePadding=0
    #).configure_axisX(labelFontSize=14)
    ).configure_axis(
    labelFontSize=12,
    titleFontSize=12
    )

heatmap

alt.Chart(...)

### Choropleth

In [18]:
# Choropleth via Altair
import altair as alt
from vega_datasets import data

alt.themes.enable("dark")

states = alt.topo_feature(data.us_10m.url, 'states')

alt.Chart(states).mark_geoshape().encode(
    color=alt.Color('population:Q', scale=alt.Scale(scheme='blues')),   # scale=color_scale
    stroke=alt.value('#154360')
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(df_selected_year, 'id', list(df_selected_year.columns))
).properties(
    width=500,
    height=300
).project(
    type='albersUsa'
)

alt.Chart(...)

In [17]:
# Choropleth via Plotly
import plotly.express as px

choropleth = px.choropleth(df_selected_year, locations='states_code', color='population', locationmode="USA-states",
                               color_continuous_scale='blues',
                               range_color=(0, max(df_selected_year.population)),
                               scope="usa",
                               labels={'population':'Population'}
                              )
choropleth.update_layout(
        template='plotly_dark',
        plot_bgcolor='rgba(0, 0, 0, 0)',
        paper_bgcolor='rgba(0, 0, 0, 0)',
        margin=dict(l=0, r=0, t=0, b=0),
        height=350
    )

choropleth